package pojos;
// Generated 26-feb-2024 19:43:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int codAlu;
     private String nombre;
     private String apellido;
     private Set notas = new HashSet(0);
     private Set telefonos = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(int codAlu, String nombre, String apellido) {
        this.codAlu = codAlu;
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Alumno(int codAlu, String nombre, String apellido, Set notas, Set telefonos) {
       this.codAlu = codAlu;
       this.nombre = nombre;
       this.apellido = apellido;
       this.notas = notas;
       this.telefonos = telefonos;
    }
   
    public int getCodAlu() {
        return this.codAlu;
    }
    
    public void setCodAlu(int codAlu) {
        this.codAlu = codAlu;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Set getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set notas) {
        this.notas = notas;
    }
    public Set getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(Set telefonos) {
        this.telefonos = telefonos;
    }




}


