package pojos;
// Generated 26-feb-2024 19:43:43 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private int codAsig;
     private String nombre;
     private int creditos;
     private Set notas = new HashSet(0);

    public Asignatura() {
    }

	
    public Asignatura(int codAsig, String nombre, int creditos) {
        this.codAsig = codAsig;
        this.nombre = nombre;
        this.creditos = creditos;
    }
    public Asignatura(int codAsig, String nombre, int creditos, Set notas) {
       this.codAsig = codAsig;
       this.nombre = nombre;
       this.creditos = creditos;
       this.notas = notas;
    }
   
    public int getCodAsig() {
        return this.codAsig;
    }
    
    public void setCodAsig(int codAsig) {
        this.codAsig = codAsig;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(int creditos) {
        this.creditos = creditos;
    }
    public Set getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set notas) {
        this.notas = notas;
    }




}


