package pojos;
// Generated 26-feb-2024 19:43:43 by Hibernate Tools 4.3.1



/**
 * NotaId generated by hbm2java
 */
public class NotaId  implements java.io.Serializable {


     private int codAlu;
     private int codAsig;

    public NotaId() {
    }

    public NotaId(int codAlu, int codAsig) {
       this.codAlu = codAlu;
       this.codAsig = codAsig;
    }
   
    public int getCodAlu() {
        return this.codAlu;
    }
    
    public void setCodAlu(int codAlu) {
        this.codAlu = codAlu;
    }
    public int getCodAsig() {
        return this.codAsig;
    }
    
    public void setCodAsig(int codAsig) {
        this.codAsig = codAsig;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotaId) ) return false;
		 NotaId castOther = ( NotaId ) other; 
         
		 return (this.getCodAlu()==castOther.getCodAlu())
 && (this.getCodAsig()==castOther.getCodAsig());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodAlu();
         result = 37 * result + this.getCodAsig();
         return result;
   }   


}


