package pojos;
// Generated 26-feb-2024 19:43:43 by Hibernate Tools 4.3.1



/**
 * Nota generated by hbm2java
 */
public class Nota  implements java.io.Serializable {


     private NotaId id;
     private Alumno alumno;
     private Asignatura asignatura;
     private int calificacion;

    public Nota() {
    }

    public Nota(NotaId id, Alumno alumno, Asignatura asignatura, int calificacion) {
       this.id = id;
       this.alumno = alumno;
       this.asignatura = asignatura;
       this.calificacion = calificacion;
    }
   
    public NotaId getId() {
        return this.id;
    }
    
    public void setId(NotaId id) {
        this.id = id;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Asignatura getAsignatura() {
        return this.asignatura;
    }
    
    public void setAsignatura(Asignatura asignatura) {
        this.asignatura = asignatura;
    }
    public int getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(int calificacion) {
        this.calificacion = calificacion;
    }




}


