package pojos;
// Generated 26-feb-2024 19:43:43 by Hibernate Tools 4.3.1



/**
 * Telefono generated by hbm2java
 */
public class Telefono  implements java.io.Serializable {


     private TelefonoId id;
     private Alumno alumno;

    public Telefono() {
    }

    public Telefono(TelefonoId id, Alumno alumno) {
       this.id = id;
       this.alumno = alumno;
    }
   
    public TelefonoId getId() {
        return this.id;
    }
    
    public void setId(TelefonoId id) {
        this.id = id;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }




}


